import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import React from "react";
import Hero from "../components/Hero";
import ServicesCards from "../components/SerivesCards";
import ServicesCards1 from "../components/SerivesCards1";
import Footer from "../components/Footer";

import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Shine </title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <container>
          <Hero className={styles.hero__image} />
        </container>
        <container>
          <ServicesCards />
          <ServicesCards1 />
        </container>
      </main>
      <footer>
        <Footer />
      </footer>
    </React.Fragment>
  );
}
